server:
  port: 8080

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123
  name: mcpflow

llm:
  base_url: https://api.deepseek.com  # api
  api_key: sk-c52cf0b318924b8384e88afae3a282ea